import type { Metadata } from "next";
import Link from "next/link";
import { DashboardPageShell } from "@/components/dashboard-page-shell";
import { IndieStorefront } from "@/components/indie-storefront";
import { getWishlistCollectablesCatalogue } from "@/lib/retailer-catalogue";

const WISHLIST_BRAND_IMAGE = "https://www.wishlistcollectables.co.uk/cdn/shop/files/IMG_20231207_152535.jpg?v=1702206733&width=1500";

export const metadata: Metadata = { title: "Wishlist Collectables | FateDrop", robots: { index: false, follow: false } };

export default async function WishlistCollectablesStorePage() {
  const products = await getWishlistCollectablesCatalogue();
  const inStock = products.filter((product) => product.available).length;
  return <DashboardPageShell title="Wishlist Collectables" eyebrow="FATEDROP INDIE STORE">
    <div className="fd-indie-substore">
      <section className="fd-dash-card fd-indie-store-hero">
        <div className="fd-dash-card-head"><span>EXPERIMENTAL FATEDROP STOREFRONT</span><i>INDIE · LONDON</i></div>
        <div className="fd-indie-store-heading"><div className="fd-indie-logo-panel" style={{ backgroundImage: `url("${WISHLIST_BRAND_IMAGE}")` }} aria-label="Wishlist Collectables storefront branding"/><div><h1>Wishlist Collectables</h1><p>Browse Wishlist Collectables inside FateDrop. Search their indexed catalogue, inspect stock and pricing here, then leave FateDrop only when you choose an item and hand off to the retailer to complete the purchase.</p><div className="fd-indie-tags"><span>Pokémon</span><span>Lorcana</span><span>One Piece</span><span>Yu-Gi-Oh</span><span>Physical store</span></div></div></div>
        <div className="fd-network-metrics"><div><strong>{products.length}</strong><span>INDEXED ITEMS</span><small>Experimental catalogue feed</small></div><div><strong>{inStock}</strong><span>IN STOCK</span><small>Feed-reported availability</small></div><div><strong>£50+</strong><span>FREE SHIPPING</span><small>UK threshold stated by retailer</small></div></div>
        <div className="fd-indie-notice"><strong>Experimental feed</strong><span>Wishlist currently states that website item prices are not being actively used. FateDrop is indexing this store to test the sub-store architecture; prices should not be treated as verified until retailer onboarding.</span></div>
      </section>
      <div className="fd-indie-substore-grid"><IndieStorefront products={products} retailerName="Wishlist Collectables" /><aside className="fd-dash-card fd-indie-store-info"><div className="fd-dash-card-head"><span>STORE INFO</span><small>FATEDROP INDEX</small></div><h2>128 Burnt Ash Road</h2><p>London · SE12 8PU</p><div className="fd-indie-info-list"><div><span>STORE TYPE</span><strong>Online + physical</strong></div><div><span>NETWORK STATUS</span><strong>Experimental candidate</strong></div><div><span>CHECKOUT</span><strong>With retailer after item selection</strong></div><div><span>DELIVERY</span><strong>Free UK £50+</strong></div></div><Link className="fd-indie-compare" href="/dashboard/true-price">Compare products across True Price →</Link></aside></div>
    </div>
    <style>{`.fd-indie-substore{display:grid;gap:22px}.fd-indie-store-hero{padding:30px}.fd-indie-store-heading{display:grid;grid-template-columns:180px 1fr;gap:24px;align-items:center;margin:18px 0 24px}.fd-indie-logo-panel{width:180px;height:120px;border:1px solid rgba(255,255,255,.12);border-radius:18px;background-color:#111;background-position:center;background-repeat:no-repeat;background-size:cover;box-shadow:0 15px 35px rgba(0,0,0,.2)}.fd-indie-store-heading h1{margin:0 0 8px;font-size:clamp(2rem,3vw,3rem);line-height:1}.fd-indie-store-heading p{margin:0;max-width:820px;color:#aaa4b0;font-size:14px;line-height:1.65}.fd-indie-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:13px}.fd-indie-tags span{padding:6px 9px;border:1px solid rgba(255,255,255,.09);border-radius:999px;color:#aaa4b0;font-size:9px;font-weight:800;letter-spacing:.06em}.fd-indie-notice{display:flex;gap:12px;margin-top:18px;padding:13px 15px;border:1px solid rgba(255,196,88,.16);border-radius:13px;background:rgba(255,196,88,.045);font-size:11px;line-height:1.5}.fd-indie-notice strong{color:#f2c56d;white-space:nowrap}.fd-indie-notice span{color:#9d97a3}.fd-indie-substore-grid{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:22px;align-items:start}.fd-indie-store-info{padding:24px;position:sticky;top:20px}.fd-indie-store-info h2{font-size:20px;margin:20px 0 4px}.fd-indie-store-info>p{color:#8e8895;font-size:12px}.fd-indie-info-list{display:grid;gap:0;margin:20px 0}.fd-indie-info-list div{display:flex;justify-content:space-between;gap:14px;padding:13px 0;border-bottom:1px solid rgba(255,255,255,.07)}.fd-indie-info-list span{font-size:8px;letter-spacing:.13em;color:#706a76}.fd-indie-info-list strong{font-size:11px;text-align:right}.fd-indie-compare{display:block;margin-top:12px;text-align:center;color:#72e8f8;font-size:10px;font-weight:800;text-decoration:none}@media(max-width:1000px){.fd-indie-substore-grid{grid-template-columns:1fr}.fd-indie-store-info{position:static}}@media(max-width:650px){.fd-indie-store-hero{padding:20px}.fd-indie-store-heading{grid-template-columns:1fr}.fd-indie-logo-panel{width:100%;height:150px}.fd-indie-notice{flex-direction:column}}`}</style>
  </DashboardPageShell>;
}
