"use client";

import type { CSSProperties } from "react";
import { AvatarAnimeCharacter } from "@/components/avatar-anime-character";
import type { AvatarLoadout } from "@/lib/avatar-loadout";
import type { NetworkSignal, SignalKind } from "@/lib/dashboard-storage";

const accents: Record<AvatarLoadout["tcgStyle"], { a: string; b: string }> = {
  neutral: { a: "#9d6dff", b: "#68e8fb" }, pokemon: { a: "#768cff", b: "#ffd86a" }, "one-piece": { a: "#ff746f", b: "#ffd06a" }, lorcana: { a: "#77dcff", b: "#b18cff" }, magic: { a: "#ff955a", b: "#9f76ff" }, yugioh: { a: "#9675ff", b: "#ff73cb" },
};

function kind(signal: NetworkSignal): SignalKind { return signal.kind ?? signal.state; }

function copy(signal: NetworkSignal) {
  const signalKind = kind(signal);
  if (signalKind === "manifested") return { kicker: "MANIFESTED", headline: "DROP DETECTED", speech: "I found live stock. Move when you’re ready.", tone: "confirmed" };
  if (signalKind === "echo") return { kicker: "ECHO DETECTED", headline: "STOCK MOVEMENT", speech: "Something just returned to the network.", tone: "confirmed" };
  if (signalKind === "drop_pulse") return { kicker: "DROP PULSE", headline: "CONDITIONS BUILDING", speech: "Several signals are lining up. I’m watching closely.", tone: "building" };
  if (signalKind === "queue") return { kicker: "QUEUE CONDITION", headline: "MAJOR NETWORK ACTIVITY", speech: "The queue changed. I’m checking for product evidence now.", tone: "surge" };
  if (signalKind === "security") return { kicker: "SECURITY CONDITION", headline: "MAJOR NETWORK ACTIVITY", speech: "Upstream conditions changed. I’m looking for corroboration.", tone: "surge" };
  return { kicker: "FATEDROP SIGNAL", headline: "NETWORK MOVEMENT", speech: "I caught a change in the network.", tone: "building" };
}

export function AvatarSignalCinematic({ signal, loadout, pulseKey, autoPulse = false }: { signal: NetworkSignal | null; loadout: AvatarLoadout; pulseKey: string; autoPulse?: boolean }) {
  const accent = accents[loadout.tcgStyle];
  const style = { "--cin-a": accent.a, "--cin-b": accent.b } as CSSProperties;
  const message = signal ? copy(signal) : { kicker: "FATEDROP NETWORK", headline: "LISTENING", speech: "I’m watching the network for you.", tone: "idle" };
  const retailer = signal?.retailer || "FateDrop Network";
  const confidence = signal?.confidence == null ? null : Math.round(signal.confidence * 100);
  const active = Boolean(signal && autoPulse);

  return <section className={`fd-avatar-cinematic tone-${message.tone} ${active ? "is-fresh" : ""}`} style={style} data-pulse-key={pulseKey}>
    <div className="fd-cinematic-space" aria-hidden="true"><i/><i/><i/><span/><span/><b/><b/></div>
    <div className="fd-cinematic-panels" aria-hidden="true"><i/><i/><i/><i/></div>
    <div className="fd-cinematic-avatar"><AvatarAnimeCharacter loadout={loadout} mood={signal ? "surge" : "watching"}/></div>
    <div className="fd-cinematic-speech"><small>YOUR FATE COMPANION</small><strong>{message.speech}</strong></div>
    <div className="fd-cinematic-beam" aria-hidden="true"><i/><i/><i/><b/></div>
    <div className="fd-cinematic-alert">
      <span>{message.kicker}</span>
      <h2>{message.headline}</h2>
      <strong>{signal?.title || "FateDrop is scanning connected sources"}</strong>
      <p>{retailer}</p>
      <div className="fd-cinematic-facts"><span><small>SIGNAL</small><b>{signal ? kind(signal).replaceAll("_", " ").toUpperCase() : "LISTENING"}</b></span><span><small>CONFIDENCE</small><b>{confidence === null ? "EVIDENCE BUILDING" : `${confidence}%`}</b></span><span><small>STATUS</small><b>{message.tone === "confirmed" ? "CONFIRMED" : message.tone === "idle" ? "MONITORING" : "WATCHING"}</b></span></div>
    </div>
    <div className="fd-cinematic-footer"><i/><span>{signal?.detail || "FateDrop is listening for queue, security, catalogue, inventory and product-level changes."}</span></div>
    <style jsx>{`
      .fd-avatar-cinematic{--cin-a:#9d6dff;--cin-b:#68e8fb;position:relative;isolation:isolate;min-height:430px;overflow:hidden;border:1px solid rgba(157,109,255,.18);border-radius:22px;background:radial-gradient(circle at 30% 35%,color-mix(in srgb,var(--cin-a) 18%,transparent),transparent 27%),linear-gradient(145deg,#080811,#080a12 56%,#05070b);box-shadow:inset 0 1px rgba(255,255,255,.04),0 24px 70px rgba(0,0,0,.24)}
      .fd-avatar-cinematic:after{content:"";position:absolute;z-index:20;inset:0;pointer-events:none;background:linear-gradient(115deg,transparent 0 48%,rgba(255,255,255,.035) 51%,transparent 54%),radial-gradient(circle at 50% 50%,transparent 48%,rgba(0,0,0,.28))}
      .fd-cinematic-space{position:absolute;inset:0;overflow:hidden;background:radial-gradient(circle at 76% 15%,rgba(104,232,251,.08),transparent 22%),radial-gradient(circle at 12% 8%,rgba(255,92,225,.1),transparent 24%)}.fd-cinematic-space i{position:absolute;width:2px;height:2px;background:#fff;border-radius:50%;left:4%;top:7%;box-shadow:40px 20px #9cefff,92px 47px #fff,176px 10px #b78cff,265px 61px #fff,360px 28px #71e9fb,460px 86px #d98aff,610px 24px #fff,780px 58px #8fefff,930px 26px #fff;opacity:.55}.fd-cinematic-space i:nth-child(2){left:8%;top:42%;transform:scale(.7)}.fd-cinematic-space span{position:absolute;left:-8%;width:72%;height:2px;background:linear-gradient(90deg,transparent,var(--cin-a),var(--cin-b),transparent);opacity:.2;transform:rotate(-12deg)}.fd-cinematic-space span:nth-of-type(1){top:27%}.fd-cinematic-space span:nth-of-type(2){top:66%;left:30%;transform:rotate(9deg)}.fd-cinematic-space b{position:absolute;border:1px solid rgba(104,232,251,.08);border-radius:50%;width:390px;height:390px;left:18%;top:-28%;box-shadow:0 0 0 42px rgba(157,109,255,.018),0 0 0 86px rgba(104,232,251,.012)}.fd-cinematic-space b:nth-of-type(2){left:auto;right:-12%;top:28%;width:280px;height:280px}
      .fd-cinematic-panels{position:absolute;inset:0;z-index:2}.fd-cinematic-panels i{position:absolute;top:13%;width:112px;height:112px;border:1px solid rgba(104,232,251,.11);border-radius:9px;background:linear-gradient(145deg,rgba(4,18,27,.66),rgba(17,8,27,.6));transform:perspective(400px) rotateY(12deg)}.fd-cinematic-panels i:after{content:"";position:absolute;inset:12px;background:repeating-linear-gradient(180deg,rgba(104,232,251,.26) 0 2px,transparent 2px 14px);opacity:.35}.fd-cinematic-panels i:nth-child(1){left:2%}.fd-cinematic-panels i:nth-child(2){left:13%;top:49%;width:85px;height:84px}.fd-cinematic-panels i:nth-child(3){right:2%;transform:perspective(400px) rotateY(-12deg)}.fd-cinematic-panels i:nth-child(4){right:13%;top:57%;width:80px;height:74px}
      .fd-cinematic-avatar{position:absolute;z-index:8;left:1%;bottom:-46px;width:430px;height:480px;animation:fdCompanionEnter .7s cubic-bezier(.2,.85,.25,1) both}.fd-cinematic-speech{position:absolute;z-index:12;left:292px;top:42px;width:230px;padding:13px 15px;border:1px solid rgba(104,232,251,.17);border-radius:14px 14px 14px 3px;background:rgba(7,10,17,.82);backdrop-filter:blur(12px);box-shadow:0 16px 40px rgba(0,0,0,.22)}.fd-cinematic-speech small{display:block;color:var(--cin-b);font-size:6px;font-weight:900;letter-spacing:.14em}.fd-cinematic-speech strong{display:block;margin-top:6px;font-size:12px;line-height:1.45}
      .fd-cinematic-beam{position:absolute;z-index:9;left:329px;top:305px;width:44%;height:86px;transform:rotate(-2deg);transform-origin:left center;pointer-events:none}.fd-cinematic-beam i{position:absolute;left:0;right:0;top:50%;height:12px;transform:translateY(-50%);border-radius:999px;background:linear-gradient(90deg,#fff,var(--cin-b) 16%,var(--cin-a) 70%,transparent);box-shadow:0 0 18px var(--cin-b),0 0 42px color-mix(in srgb,var(--cin-a) 70%,transparent);opacity:.82}.fd-cinematic-beam i:nth-child(2){height:3px;filter:blur(.3px);opacity:1}.fd-cinematic-beam i:nth-child(3){height:42px;background:linear-gradient(90deg,color-mix(in srgb,var(--cin-b) 28%,transparent),color-mix(in srgb,var(--cin-a) 18%,transparent),transparent);filter:blur(10px)}.fd-cinematic-beam b{position:absolute;left:-13px;top:50%;width:46px;height:46px;border:3px solid var(--cin-b);border-radius:50%;transform:translateY(-50%);box-shadow:0 0 22px var(--cin-b),inset 0 0 18px var(--cin-a);background:radial-gradient(circle,#fff 0 12%,var(--cin-b) 13% 22%,transparent 24%)}
      .fd-cinematic-alert{position:absolute;z-index:10;right:5%;top:72px;width:min(46%,590px);padding:25px 26px 22px;border:1px solid color-mix(in srgb,var(--cin-a) 42%,transparent);clip-path:polygon(18px 0,100% 0,100% calc(100% - 18px),calc(100% - 18px) 100%,0 100%,0 18px);background:linear-gradient(145deg,rgba(13,12,23,.95),rgba(5,8,14,.96));box-shadow:0 0 0 1px rgba(104,232,251,.04),0 0 50px color-mix(in srgb,var(--cin-a) 13%,transparent),0 24px 55px rgba(0,0,0,.32);animation:fdAlertMaterialise .55s .22s ease-out both}.fd-cinematic-alert:before,.fd-cinematic-alert:after{content:"";position:absolute;width:54px;height:2px;background:var(--cin-b);box-shadow:0 0 12px var(--cin-b)}.fd-cinematic-alert:before{left:18px;top:0}.fd-cinematic-alert:after{right:18px;bottom:0}.fd-cinematic-alert>span{color:var(--cin-b);font-size:8px;font-weight:900;letter-spacing:.18em}.fd-cinematic-alert h2{margin:7px 0 9px;font-size:clamp(1.8rem,3.3vw,3.7rem);line-height:.88;letter-spacing:-.055em;background:linear-gradient(90deg,#fff,#c9f8ff 45%,#c2a2ff);-webkit-background-clip:text;color:transparent}.fd-cinematic-alert>strong{display:block;font-size:14px;line-height:1.35}.fd-cinematic-alert>p{margin:5px 0 18px;color:#8e8795;font-size:10px}.fd-cinematic-facts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.fd-cinematic-facts span{padding:9px;border:1px solid rgba(255,255,255,.06);border-radius:9px;background:rgba(0,0,0,.18)}.fd-cinematic-facts small{display:block;color:#625c69;font-size:5px;font-weight:900;letter-spacing:.11em}.fd-cinematic-facts b{display:block;margin-top:3px;color:#d8d3dc;font-size:8px}.tone-confirmed .fd-cinematic-alert{border-color:rgba(95,239,169,.28)}.tone-confirmed .fd-cinematic-alert>span{color:#6decae}.tone-building .fd-cinematic-alert>span{color:#c9a4ff}
      .fd-cinematic-footer{position:absolute;z-index:11;left:26px;right:26px;bottom:18px;display:flex;gap:8px;align-items:center;color:#77717e;font-size:8px}.fd-cinematic-footer i{width:7px;height:7px;border-radius:50%;background:var(--cin-b);box-shadow:0 0 12px var(--cin-b)}
      .is-fresh .fd-cinematic-beam{animation:fdBeamFire .95s cubic-bezier(.2,.8,.25,1) both}.is-fresh .fd-cinematic-space span{animation:fdSpaceReact 1.2s ease-out both}.is-fresh .fd-cinematic-alert{animation:fdAlertMaterialise .55s .35s ease-out both,fdAlertGlow 1.8s .8s ease-out both}
      @keyframes fdCompanionEnter{from{opacity:0;transform:translateX(-55px) scale(.92)}to{opacity:1;transform:none}}@keyframes fdBeamFire{0%{opacity:0;transform:rotate(-2deg) scaleX(.04)}25%{opacity:1}70%{transform:rotate(-2deg) scaleX(1.08)}100%{transform:rotate(-2deg) scaleX(1)}}@keyframes fdAlertMaterialise{from{opacity:0;transform:translateX(35px) scale(.97);filter:blur(7px)}to{opacity:1;transform:none;filter:none}}@keyframes fdAlertGlow{0%{filter:brightness(1)}45%{filter:brightness(1.24)}100%{filter:brightness(1)}}@keyframes fdSpaceReact{from{opacity:.1}50%{opacity:.58}to{opacity:.2}}
      @media(max-width:980px){.fd-avatar-cinematic{min-height:520px}.fd-cinematic-avatar{left:-5%;bottom:-68px;width:370px}.fd-cinematic-speech{left:210px;top:32px}.fd-cinematic-beam{left:265px;top:330px;width:48%}.fd-cinematic-alert{right:3%;top:165px;width:52%}}@media(max-width:720px){.fd-avatar-cinematic{min-height:650px}.fd-cinematic-avatar{left:50%;bottom:125px;width:330px;transform:translateX(-50%)}.fd-cinematic-speech{left:16px;top:20px;width:210px}.fd-cinematic-beam{display:none}.fd-cinematic-alert{left:16px;right:16px;top:auto;bottom:54px;width:auto}.fd-cinematic-facts{grid-template-columns:1fr 1fr 1fr}.fd-cinematic-footer{left:16px;right:16px;bottom:15px}.fd-cinematic-panels{opacity:.35}}@media(prefers-reduced-motion:reduce){.fd-cinematic-avatar,.fd-cinematic-alert,.fd-cinematic-beam,.fd-cinematic-space span{animation:none!important}}
    `}</style>
  </section>;
}
