import type { Metadata } from "next";
import Link from "next/link";
import { DashboardPageShell } from "@/components/dashboard-page-shell";
import { getCobAndPipCatalogue, getWishlistCollectablesCatalogue } from "@/lib/retailer-catalogue";

export const metadata: Metadata = { title: "Indie Stores | FateDrop Dashboard", robots: { index: false, follow: false } };

export default async function DashboardStoresPage() {
  const [cobAndPip, wishlist] = await Promise.all([getCobAndPipCatalogue(), getWishlistCollectablesCatalogue()]);
  const stores = [
    { id: "wishlist-collectables", name: "Wishlist Collectables", location: "London · Online + physical", tags: ["Pokémon", "Lorcana", "One Piece", "Yu-Gi-Oh"], products: wishlist, href: "/dashboard/stores/wishlist-collectables", note: "Experimental sub-store" },
    { id: "cob-and-pip", name: "Cob & Pip", location: "UK · Online", tags: ["Pokémon", "TCG"], products: cobAndPip, href: "https://cobandpip.co.uk", note: "Sub-store coming next" },
  ];
  const indexed = stores.reduce((total, store) => total + store.products.length, 0);

  return <DashboardPageShell title="Indie Stores" eyebrow="DISCOVER THE FATEDROP RETAILER NETWORK">
    <div className="fd-indie-hub">
      <section className="fd-dash-card fd-indie-hub-hero"><div className="fd-dash-card-head"><span>INDEPENDENT NETWORK</span><i className="live">● {stores.length} STORES IN LAB</i></div><div className="fd-network-message"><h1>Walk into a store. Browse their world.</h1><p>Indie Stores is for discovering independent retailers and entering their own FateDrop sub-store. Product-vs-product comparison belongs in True Price; this is where the retailers themselves get an identity.</p></div><div className="fd-network-metrics"><div><strong>{stores.length}</strong><span>INDIE STORES</span><small>Experimental network</small></div><div><strong>{indexed}</strong><span>INDEXED ITEMS</span><small>Across connected indie feeds</small></div><div><strong>1</strong><span>SUB-STORE LIVE</span><small>Wishlist experiment</small></div></div></section>

      <section className="fd-dash-card fd-indie-discovery"><div className="fd-dash-card-head"><span>STORE DIRECTORY</span><Link href="/dashboard/true-price">Need a product? Open True Price ↗</Link></div><div className="fd-indie-store-grid">{stores.map((store) => { const inStock = store.products.filter((product) => product.available).length; return <article className="fd-indie-store-card" key={store.id}><div className="fd-indie-store-card-top"><span className="fd-indie-store-logo">{store.name.split(" ").map((word) => word[0]).join("").slice(0,2)}</span><span className="fd-indie-store-status">{store.note}</span></div><h2>{store.name}</h2><p>{store.location}</p><div className="fd-indie-store-tags">{store.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="fd-indie-store-stats"><div><strong>{store.products.length}</strong><small>INDEXED</small></div><div><strong>{inStock}</strong><small>IN STOCK</small></div></div>{store.href.startsWith("http") ? <a className="fd-indie-store-open" href={store.href} target="_blank" rel="noreferrer">Visit retailer ↗</a> : <Link className="fd-indie-store-open" href={store.href}>Enter FateDrop store →</Link>}</article>; })}</div></section>

      <section className="fd-dash-card fd-indie-model"><div><span>HOW THIS DIFFERS FROM TRUE PRICE</span><h2>Stores are destinations. True Price is the comparison engine.</h2></div><p>Browse an indie here when you want to explore that retailer. Jump to True Price when you already know the product and want FateDrop to compare every matching offer across the wider network.</p></section>
    </div>
    <style>{`.fd-indie-hub{display:grid;gap:22px}.fd-indie-hub-hero{padding:30px}.fd-indie-hub-hero .fd-network-message h1{font-size:clamp(2rem,3vw,3.2rem);line-height:1.02;max-width:850px}.fd-indie-hub-hero .fd-network-message p{font-size:15px;line-height:1.7;max-width:900px}.fd-indie-discovery{padding:28px}.fd-indie-store-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:22px}.fd-indie-store-card{min-height:330px;padding:22px;display:flex;flex-direction:column;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:radial-gradient(circle at 90% 0%,rgba(157,109,255,.1),transparent 34%),rgba(255,255,255,.022)}.fd-indie-store-card-top{display:flex;align-items:center;justify-content:space-between;gap:12px}.fd-indie-store-logo{width:52px;height:52px;display:grid;place-items:center;border:1px solid rgba(88,232,255,.25);border-radius:15px;background:linear-gradient(135deg,rgba(88,232,255,.1),rgba(157,109,255,.13));font-size:16px;font-weight:900}.fd-indie-store-status{font-size:8px;letter-spacing:.1em;text-transform:uppercase;color:#8d8795}.fd-indie-store-card h2{margin:20px 0 5px;font-size:24px}.fd-indie-store-card>p{margin:0;color:#89838f;font-size:12px}.fd-indie-store-tags{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0}.fd-indie-store-tags span{padding:6px 8px;border:1px solid rgba(255,255,255,.08);border-radius:999px;font-size:8px;color:#aaa4b0}.fd-indie-store-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:auto}.fd-indie-store-stats div{padding:12px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.025)}.fd-indie-store-stats strong{display:block;font-size:19px}.fd-indie-store-stats small{font-size:7px;letter-spacing:.12em;color:#77717d}.fd-indie-store-open{margin-top:14px;min-height:42px;display:grid;place-items:center;border:1px solid rgba(88,232,255,.25);border-radius:12px;background:linear-gradient(135deg,rgba(88,232,255,.08),rgba(157,109,255,.1));color:#fff;font-size:10px;font-weight:850;text-decoration:none}.fd-indie-model{padding:24px 28px;display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center}.fd-indie-model span{font-size:8px;letter-spacing:.15em;color:#68e8fb;font-weight:850}.fd-indie-model h2{margin:7px 0 0;font-size:22px}.fd-indie-model p{margin:0;color:#96909c;font-size:12px;line-height:1.65}@media(max-width:850px){.fd-indie-store-grid,.fd-indie-model{grid-template-columns:1fr}.fd-indie-hub-hero,.fd-indie-discovery{padding:20px}}`}</style>
  </DashboardPageShell>;
}
